export default {
  vehicles: [
    {
      id: 1,
      make: 'Toyota',
      model: 'Corolla',
      status: 'Parked',
      last_contact: 45,
      ignition: 'off',
      battery_voltage: 12.3,
      fuel_level: 78,
      vin: '1HGCM82633A004352',
      engine_errors: [
        { code: 'P0171', description: 'Fuel System Too Lean' },
        { code: 'TPMS', description: 'Tire Pressure 32 PSI (Front Left)' },
      ],
      address: 'Vitosha Boulevard, Sofia, Bulgaria',
      coordinates: { lat: 42.6886, lng: 23.3198 },
    },
    {
      id: 2,
      make: 'Volkswagen',
      model: 'Golf',
      status: 'Moving',
      last_contact: 2,
      ignition: 'on',
      battery_voltage: 14.1,
      fuel_level: 42,
      vin: 'WVWZZZ1KZ8W357896',
      engine_errors: [
        { code: 'P0300', description: 'Random/Multiple Cylinder Misfire' },
        { code: 'U1123', description: 'Data Bus Fault' },
      ],
      address: 'Tsarigradsko Shose, Sofia, Bulgaria',
      coordinates: { lat: 42.6507, lng: 23.3794 },
    },
    {
      id: 3,
      make: 'BMW',
      model: 'X5',
      status: 'Parked',
      last_contact: 38,
      ignition: 'off',
      battery_voltage: 12.1,
      fuel_level: 91,
      vin: 'WBAFR9C58BC082763',
      engine_errors: [
        { code: 'P313', description: 'Check Engine' },
        { code: 'A0B4', description: 'Hybrid Battery Fault' },
        { code: 'TPMS', description: 'Tire Pressure 29 PSI (Rear Right)' },
      ],
      address: 'Studentski Grad, Sofia, Bulgaria',
      coordinates: { lat: 42.6509, lng: 23.3635 },
    },
    {
      id: 4,
      make: 'Mercedes',
      model: 'C-Class',
      status: 'Moving',
      last_contact: 4,
      ignition: 'on',
      battery_voltage: 13.9,
      fuel_level: 35,
      vin: 'WDDGF8BB8AF000782',
      engine_errors: [
        { code: 'B1647', description: 'Fuel Pump Circuit Malfunction' },
        { code: 'C1023', description: 'ABS Sensor Fault' },
      ],
      address: 'Ring Road, Sofia, Bulgaria',
      coordinates: { lat: 42.6253, lng: 23.3601 },
    },
    {
      id: 5,
      make: 'Ford',
      model: 'Focus',
      status: 'Parked',
      last_contact: 52,
      ignition: 'off',
      battery_voltage: 12.5,
      fuel_level: 65,
      vin: '1FADP3F21FL300447',
      engine_errors: [
        {
          code: 'P0420',
          description: 'Catalyst System Efficiency Below Threshold',
        },
        {
          code: 'U0126',
          description: 'Lost Communication with Steering Control Module',
        },
      ],
      address: 'Oborishte, Sofia, Bulgaria',
      coordinates: { lat: 42.6977, lng: 23.3357 },
    },
    {
      id: 6,
      make: 'Audi',
      model: 'A4',
      status: 'Moving',
      last_contact: 1,
      ignition: 'on',
      battery_voltage: 14.2,
      fuel_level: 28,
      vin: 'WAUZZZ8K9FA123456',
      engine_errors: [
        { code: 'P0299', description: 'Turcharger Underboost' },
        { code: 'TPMS', description: 'Tire Pressure 31 PSI (Front Right)' },
        { code: 'B1245', description: 'Climate Control Fault' },
      ],
      address: 'Mladost 1, Sofia, Bulgaria',
      coordinates: { lat: 42.6564, lng: 23.3759 },
    },
    {
      id: 7,
      make: 'Nissan',
      model: 'Qashqai',
      status: 'Parked',
      last_contact: 67,
      ignition: 'off',
      battery_voltage: 12.0,
      fuel_level: 83,
      vin: 'SJNFDAJ11U2123456',
      engine_errors: [
        { code: 'P0328', description: 'Knock Sensor Circuit High Input' },
        { code: 'C1145', description: 'ESP System Malfunction' },
      ],
      address: 'Lyulin, Sofia, Bulgaria',
      coordinates: { lat: 42.7146, lng: 23.2702 },
    },
    {
      id: 8,
      make: 'Peugeot',
      model: '308',
      status: 'Moving',
      last_contact: 3,
      ignition: 'on',
      battery_voltage: 13.8,
      fuel_level: 47,
      vin: 'VF3***************',
      engine_errors: [
        {
          code: 'P1351',
          description: 'Ignition Coil Control Circuit High Voltage',
        },
        { code: 'U1105', description: 'Steering Angle Sensor Fault' },
      ],
      address: 'Botevgradsko Shose, Sofia, Bulgaria',
      coordinates: { lat: 42.6972, lng: 23.3754 },
    },
  ],
};
